[package]
name = "lenses"
version = "0.1.0"
authors = ["Santiago Saavedra <info@ssaavedra.eu>"]
edition = "2018"
license = "Apache-2.0"
description = "An optics library loosely inspired by Julien Truffaut's Monocle"

